CREATE TABLE GatherGoal (
	Stage			INTEGER		NOT NULL,
	Mission			VARCHAR(36) NOT NULL,
	Material		VARCHAR(50)	NOT NULL,

	PRIMARY KEY(Stage,Mission),
	CONSTRAINT gthglfk1 FOREIGN KEY(Stage,Mission)	REFERENCES MissionGoal(Stage,Mission) ON UPDATE CASCADE ON DELETE CASCADE
);