CREATE TABLE ItemReward (
	TypeID			VARCHAR(36)		NOT NULL	PRIMARY KEY,
	ItemStack		VARCHAR(200),

	CONSTRAINT irdrdfk1 FOREIGN KEY(TypeID) REFERENCES RewardType(TypeID) ON UPDATE CASCADE ON DELETE CASCADE
);
