CREATE TABLE MissionBearer (
	UUID				VARCHAR(36)	NOT NULL	PRIMARY KEY,
	CooldownStart		BIGINT,
	CooldownDuration	BIGINT,
	PrimaryMission		VARCHAR(36),
	BearerType			VARCHAR(20) NOT NULL
);

CREATE TABLE Mission (
	UUID				VARCHAR(36)	NOT NULL	PRIMARY KEY,
	MissionBearer		VARCHAR(36)	NOT NULL,
	Duration			BIGINT,
	StartTime			BIGINT,
	Stage				INT			NOT NULL,

	CONSTRAINT mfk FOREIGN KEY(MissionBearer) REFERENCES MissionBearer(UUID) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE MissionGoal (
	 Mission		VARCHAR(36)	NOT NULL,
	 Stage			INTEGER		NOT NULL,
	 GoalAmount		INTEGER		NOT NULL,
	 Definition		VARCHAR(36)	NOT NULL,
	 Progress		INTEGER,

	 PRIMARY KEY(Stage,Mission),
	 CONSTRAINT mgfk FOREIGN KEY(Mission) REFERENCES Mission(UUID) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE Contribution (
	UUID			VARCHAR(36)	NOT NULL,
	Goal			INTEGER		NOT NULL,
	Mission			VARCHAR(36) NOT NULL,
	Amount			INTEGER,

	PRIMARY KEY(UUID,Goal,Mission),
	CONSTRAINT contfk FOREIGN KEY(Goal,Mission) REFERENCES MissionGoal(Stage,Mission) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE RewardType (
	TypeID			VARCHAR(36)	NOT NULL	PRIMARY KEY,
	Type			VARCHAR(20)	NOT NULL
);

CREATE TABLE MissionReward (
	RewardID		VARCHAR(36)	NOT NULL	PRIMARY KEY,
	Mission			VARCHAR(36)	NOT NULL,
	Amount			DECIMAL(10,3),
	RewardType		VARCHAR(36)	NOT NULL,

	CONSTRAINT mrwrdfk1 FOREIGN KEY(Mission) REFERENCES Mission(UUID) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT mrwrdfk2 FOREIGN KEY(RewardType) REFERENCES RewardType(TypeID) ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE GoalReward (
	RewardID		VARCHAR(36)	NOT NULL	PRIMARY KEY,
	Goal			INTEGER		NOT NULL,
	Mission			VARCHAR(36)	NOT NULL,
	RewardType		VARCHAR(36)		NOT NULL,
	Amount			DECIMAL(10,3),

	CONSTRAINT grfk1 FOREIGN KEY(Goal,Mission) REFERENCES MissionGoal(Stage,Mission) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT frfk2 FOREIGN KEY(RewardType) REFERENCES RewardType(TypeID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OfflineReward (
	RewardID		INTEGER		NOT NULL	PRIMARY KEY     AUTOINCREMENT,
	PlayerID		VARCHAR(36)	NOT NULL,
	Amount			DECIMAL(10,3),
	RewardType		VARCHAR(36)		NOT NULL,

	CONSTRAINT ofrfk1 FOREIGN KEY(RewardType) REFERENCES RewardType(TypeID) ON UPDATE CASCADE ON DELETE CASCADE
);



