names:
  boss: 'Aliens'
  players: 'Humans'

events:
  AlienInvasion:
    type: 'BOSS'
    world: 'invasion'
    display-name: '&e&lAlien Invasion'
    bosses:
      1:
        name: 'Alien'
        spawn-location:
          x: 130
          y: 90
          z: -72

    topNRewards:
      top1:
        n: 1
        rewards:
          1:
            type: item
            amount: 1
            name: "&fDragon Egg"
            itemstack:
              ==: org.bukkit.inventory.ItemStack
              v: 19
              type: dragon_egg
          2:
            type: command
            name: "500 XP"
            command: "minecraft:xp add {0} 500"
      top2:
        n: 2
        rewards:
          1:
            type: command
            name: "$75"
            command: "money grant {0} 75"
          2:
            type: item
            amount: 3
            name: "&fEnd Crystal"
            itemstack:
              ==: org.bukkit.inventory.ItemStack
              v: 19
              type: end_crystal

